package automationTests;

//Generated by Selenium IDE
import freemarker.template.TemplateException;
import io.github.sridharbandi.HtmlCsRunner;
import io.github.sridharbandi.a11y.HTMLCS;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.After;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import static org.junit.Assert.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import pages.*;

import java.net.URISyntaxException;
import java.util.*;
import java.io.IOException;

public class selectItem {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private Logger logger;
    private BaseTestClass baseTestClass;
    private static HtmlCsRunner htmlCsRunner;

    @Before

    public void setUp() throws IOException {
        driver = baseTestClass.initializeDriver();
        htmlCsRunner = new HtmlCsRunner(driver);
        htmlCsRunner.setStandard(HTMLCS.WCAG2A);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        logger = LogManager.getLogger(selectItem.class);
        logger.info("opening webiste");

    }
    @After
    public void tearDown() throws TemplateException, IOException, URISyntaxException {
        htmlCsRunner.execute();
        // driver.quit();
        htmlCsRunner.generateHtmlReport();
    }

    @Test
    public void selectFromHome() {
        // Test: select item from home
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://atid.store/");
        // 2 | setWindowSize | 1052x666 |
        driver.manage().window().setSize(new Dimension(1052, 666));
        // 3 | open item
        logger.debug("open item");
        HomePage homePage = new HomePage(driver);
        homePage.ClickOnItemAtHomePage();

        assertEquals("https://atid.store/product/atid-yellow-shoes/", driver.getCurrentUrl());
        logger.debug("test pass");
    }

    @Test
    public void selectFromStore() {
        // Test: select item from store
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://atid.store/");
        // 2 | setWindowSize | 1052x666 |
        driver.manage().window().setSize(new Dimension(1052, 666));
        logger.debug("go to store");
        StorePage storePage = new StorePage(driver);
        storePage.clickStoreBtn();
        logger.debug("open item");
        ProductPage productPage = new ProductPage(driver);
        productPage.clickProductBtn();
        logger.debug("check if succeed");
        assertEquals("https://atid.store/product/anchor-bracelet/", driver.getCurrentUrl());
        logger.debug("test pass");
    }

    @Test
    public void selectFromWomen() {
        // Test: select item from women
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://atid.store/");
        // 2 | setWindowSize | 1052x666 |
        driver.manage().window().setSize(new Dimension(1052, 666));
        logger.debug("go to women store");
        WomenPage womenPage = new WomenPage(driver);
        womenPage.ClickOnWomenPage();
        logger.debug("open item");
        womenPage.ClickOnIemInWomenPage();
        logger.debug("check if succeed");
        assertEquals("https://atid.store/product/blue-denim-jeans/", driver.getCurrentUrl());
        logger.debug("test pass");
    }

    @Test
    public void selectFromMen() {
        // Test: select item from men
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://atid.store/");
        // 2 | setWindowSize | 1052x666 |
        driver.manage().window().setSize(new Dimension(1052, 666));
        logger.debug("go to men store");
        MenPage menPage = new MenPage(driver);
        menPage.ClickOnMenPage();
        logger.debug("open item");
        menPage.ClickOnIemInMenPage();
        logger.debug("check if succeed");
        assertEquals("https://atid.store/product/atid-blue-shoes/", driver.getCurrentUrl());
        logger.debug("test pass");
    }

    @Test
    public void selectFromAccessories() {
        // Test: select item from accessories
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://atid.store/");
        // 2 | setWindowSize | 1052x666 |
        driver.manage().window().setSize(new Dimension(1052, 666));
        logger.debug("go to accessories store");
        AccessoriesPage accessoriesPage = new AccessoriesPage(driver);
        accessoriesPage.ClickOnAccessoriesPage();
        logger.debug("open item");
        accessoriesPage.ClickOnIemInAccessoriesPage();
        logger.debug("check if succeed");
        assertEquals("https://atid.store/product/bright-gold-purse-with-chain/", driver.getCurrentUrl());
        logger.debug("test pass");
    }

    public static void main(String args[]) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(selectItem.class); // Replace "SampleTest" with the name of your class
        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}

